name: Honkai Star Rail Repository List Automation

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: 0 17 * * *

jobs:
  action-preparation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Git
        run: |
          git --version

  auto-fetching:
    runs-on: ubuntu-latest
    steps:
      - name: Save Current Date To GitHub Environment
        run: |
          echo "CURRENT_DATE=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      # - name: Fetch OS 
      #   uses: JamesIves/fetch-api-data-action@v2
      #   with:
      #     endpoint: "https://hkrpg-launcher-static.hoyoverse.com/hkrpg_global/mdk/launcher/api/resource?channel_id=1&key=vplOVX8Vn7cwG8yb&launcher_id=35&sub_channel_id=0"
      #     save-location: "OS/original/"
      #     save-name: result-${{ env.CURRENT_DATE }}
      - name: Fetch OS
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: "https://sg-hyp-api.hoyoverse.com/hyp/hyp-connect/api/getGamePackages?launcher_id=VYTpXlbWo8&game_ids[]=4ziysqXOQ8"
          save-location: "OS/prettier/"
          save-name: result-${{ env.CURRENT_DATE }}
      # - name: Fetch CN
      #   uses: JamesIves/fetch-api-data-action@v2
      #   with:
      #     endpoint: "https://api-launcher.mihoyo.com/hkrpg_cn/mdk/launcher/api/resource?channel_id=1&key=6KcVuOkbcqjJomjZ&launcher_id=33&sub_channel_id=0"
      #     save-location: "CN/original/"
      #     save-name: result-${{ env.CURRENT_DATE }}
      - name: Fetch CN
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: "https://hyp-api.mihoyo.com/hyp/hyp-connect/api/getGamePackages?launcher_id=jGHBHlcOq1&game_ids[]=64kMb5iAWu"
          save-location: "CN/prettier/"
          save-name: result-${{ env.CURRENT_DATE }}
      - name: Code File Prettier
        run: |
          npx prettier --write OS/prettier/**/*.json
          npx prettier --write CN/prettier/**/*.json
      - name: Commit Changes
        run: |
          git config --local user.name "sxjeru"
          git config --local user.email "sxjeru@users.noreply.github.com"

          arr[0]="Daily Fetch Commit Automation (Bot) 🏠"
          arr[1]="Daily Fetch Commit Automation (Bot) 🏘️"
          arr[2]="Daily Fetch Commit Automation (Bot) 🏡"
          arr[3]="Daily Fetch Commit Automation (Bot) 🏨"
          arr[4]="Daily Fetch Commit Automation (Bot) 🏪"
          arr[5]="Daily Fetch Commit Automation (Bot) 🏦"
          arr[6]="Daily Fetch Commit Automation (Bot) 🏢"
          arr[7]="Daily Fetch Commit Automation (Bot) 🏭"
          rand=$[$RANDOM % ${#arr[@]}]

          git add ./OS/
          git add ./CN/
          git commit -m "${arr[$rand]}"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
